language: go

before_install:
  - go get -t -v ./...

script:
  - go test ./client/one -race -coverprofile=coverage.txt -covermode=atomic
  - go test ./client/two -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

git:
  depth: 1
